#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/janfki/anaconda3"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/janfki/anaconda3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/janfki/Desktop/put_neuron_here/minimized/x86_64/.libs/libnrnmech.so" "$@"
